#!/bin/bash

# just a lone test file for now
# tests=test.descr

a.out test.descr > test.out

echo "diff of test.out and test.ans should print nothing below this line"
diff test.out test.ans

#end of file

